import {
    databaseUserRestaurant,
    getUserRestuarant,
    registerUserRestaurant,
    referenceUser,
    referenceUserRestaurant,
} from './serviceUser'

import {
    referenceDevice,
    databaseDevice,
    getAllDevices,
    updateDevice,
    removeDevice,
} from './serviceDevice'

import {
    referenceDishe,
    referenceFood,
    referenceDrink,
    referenceCombo,
    referenceDessert,
    databaseDishe,
    getFoods,
    getDrinks,
    getDesserts,
    getCombos,
    updateProduct,
    deleteProduct,
    nameFood,
    nameDrink,
    nameDessert,
    nameCombo,
    products,
    getProduct,
} from './serviceDishe'

export {
    databaseUserRestaurant,
    getUserRestuarant,
    registerUserRestaurant,
    referenceUser,
    referenceUserRestaurant,
    referenceDevice,
    databaseDevice,
    getAllDevices,
    updateDevice,
    removeDevice,
    referenceDishe,
    referenceFood,
    referenceDrink,
    referenceCombo,
    referenceDessert,
    databaseDishe,
    getFoods,
    getDrinks,
    getDesserts,
    getCombos,
    updateProduct,
    deleteProduct,
    nameFood,
    nameDrink,
    nameDessert,
    nameCombo,
    products,
    getProduct,
}
