import { createUUID } from './generate'
import { sizeString, blank } from './errorMessage'
import {
    getAccess,
    authentification,
    nameDevice,
    nameDishe,
    nameOrder,
    nameRegister,
    nameMain,
    nameHome,
    urlDevice,
    urlDishe,
    urlOrder,
    urlRegister,
    urlMain,
    urlHome,
    jobs,
} from './accessUserRestaurant'

export {
    createUUID,
    getAccess,
    authentification,
    nameDevice,
    nameDishe,
    nameOrder,
    nameRegister,
    urlDevice,
    urlDishe,
    urlOrder,
    urlRegister,
    urlMain,
    urlHome,
    sizeString,
    blank,
    jobs,
    nameHome,
    nameMain,
}
